import { test, expect } from '@playwright/test';

test('pantalla inicial muestra propuestas ficticias, horarios locales, detalles y copia', async ({ page, context }) => {
  await context.grantPermissions(['clipboard-read', 'clipboard-write']);
  const errors = [];
  page.on('pageerror', error => errors.push(error.message));
  await page.goto('/');
  await expect(page.getByText('Modo demostración', { exact: true })).toBeVisible();
  await expect(page.locator('.parlay-card')).toHaveCount(6);
  await expect(page.locator('.demo-pill').first()).toHaveText('DEMO');
  await expect(page.locator('.card-update').first()).toContainText('Hora de Chile');
  const first = page.locator('.parlay-card').first();
  await first.getByRole('button', { name: 'Ver detalles' }).click();
  await expect(first.getByText(/Probabilidad implícita/)).toBeVisible();
  await expect(first.getByText(/No hay estadísticas/).first()).toBeVisible();
  await first.getByRole('button', { name: 'Copiar combinada' }).click();
  await expect(page.getByRole('status')).toContainText('copiada');
  const clipboard = await page.evaluate(() => navigator.clipboard.readText());
  expect(clipboard).toContain('FICTICIOS');
  expect(clipboard).toContain('America/Santiago');
  expect(clipboard).toContain('Cuota total');
  expect(errors).toEqual([]);
});

test('filtros del día alteran deportes, mercados y resultados vacíos sin datos inventados', async ({ page }) => {
  await page.goto('/');
  await expect(page.locator('.parlay-card')).toHaveCount(6);
  await page.locator('.sport-tabs').getByRole('button', { name: 'Tenis' }).click();
  await expect(page.locator('.parlay-card').first()).toBeVisible();
  await expect(page.locator('.legs-list').filter({ hasText: 'Liga Iberia' })).toHaveCount(0);
  await page.getByRole('button', { name: 'Filtros', exact: true }).click();
  await page.getByRole('spinbutton', { name: 'Cuota total mínima' }).fill('100');
  await expect(page.getByRole('heading', { name: 'No hay propuestas con estos filtros' })).toBeVisible();
  await expect(page.locator('.parlay-card')).toHaveCount(0);
  await page.getByRole('button', { name: 'Limpiar filtros' }).click();
  await expect(page.locator('.parlay-card')).toHaveCount(6);
});

test('constructor genera un producto válido y explica alternativas fuera del margen', async ({ page }) => {
  await page.goto('/');
  await page.locator('.desktop-nav').getByRole('button', { name: 'Crear combinada' }).click();
  await page.locator('.sport-options').getByRole('button', { name: 'Fútbol' }).click();
  const responsePromise = page.waitForResponse(response => response.url().endsWith('/api/parlays/build') && response.request().method() === 'POST');
  await page.locator('button[type="submit"]').click();
  const result = await (await responsePromise).json();
  expect(result.status).toBe('matched');
  const product = result.parlay.legs.reduce((value, leg) => value * leg.odds, 1);
  expect(Math.abs(result.parlay.totalOdds - product)).toBeLessThan(0.000001);
  expect(new Set(result.parlay.legs.map(leg => leg.eventId)).size).toBe(3);
  expect(new Set(result.parlay.legs.map(leg => leg.bookmakerKey)).size).toBe(1);
  await expect(page.getByRole('heading', { name: 'Una combinada a tu medida.' })).toBeVisible();
  await page.getByRole('spinbutton', { name: 'Cuota total objetivo' }).fill('50');
  await page.locator('button[type="submit"]').click();
  await expect(page.getByRole('heading', { name: 'No hay una coincidencia exacta.' })).toBeVisible();
  await expect(page.getByRole('heading', { name: 'Alternativas fuera del margen solicitado' })).toBeVisible();
});

test('sin clave, el chat explica la conexión pendiente y no simula respuestas', async ({ page }) => {
  await page.goto('/');
  await page.locator('.desktop-nav').getByRole('button', { name: 'Asistente IA' }).click();
  await expect(page.getByText('IA pendiente de conexión')).toBeVisible();
  await page.getByRole('textbox', { name: 'Mensaje al asistente IA' }).fill('cambia el segundo partido');
  await expect(page.getByRole('button', { name: 'Enviar mensaje' })).toBeDisabled();
  await expect(page.locator('.chat-entry.assistant')).toHaveCount(0);
});

test('chat conectado conserva propuesta para seguimiento y muestra filtros y resultados actualizados', async ({ page }) => {
  // Only the remote interpretation transport is controlled here. Proposals and replacements
  // are generated by the running API engine; no remote AI service is claimed by this test.
  let lastPrevious;
  let lastResult;
  await page.route('**/api/status', async route => {
    const response = await route.fetch();
    const data = await response.json();
    await route.fulfill({ json: { ...data, ai: { configured: true, model: 'Modelo de prueba de transporte' } } });
  });
  await page.route('**/api/chat', async route => {
    const request = route.request().postDataJSON();
    const replacing = request.message.includes('segundo');
    const removing = request.message.includes('quita');
    lastPrevious = request.previous;
    const filters = {
      ...request.filters, sports: removing ? ['basketball'] : ['tennis', 'basketball'],
      legCount: 4, targetOdds: 3, tolerance: 0.8,
    };
    const response = await page.request.post('/api/parlays/build', {
      data: { filters, ...(replacing ? { previous: request.previous, replaceIndex: 1 } : {}) },
    });
    lastResult = await response.json();
    await route.fulfill({ json: { message: 'Resultado del transporte de prueba sobre eventos ficticios.', filters, result: lastResult, mode: 'demo', aiMode: 'live', changes: removing ? ['sports'] : replacing ? ['selection:2'] : ['sports', 'legCount', 'targetOdds'] } });
  });
  await page.goto('/');
  await page.locator('.desktop-nav').getByRole('button', { name: 'Asistente IA' }).click();
  const textbox = page.getByRole('textbox', { name: 'Mensaje al asistente IA' });
  await textbox.fill('Combina tenis y básquetbol con 4 partidos y cuota 3,00');
  await page.getByRole('button', { name: 'Enviar mensaje' }).click();
  await expect(page.locator('.chat-entry.assistant')).toHaveCount(1);
  await expect(page.locator('.chat-entry.assistant').first().getByText('Filtros interpretados')).toBeVisible();
  expect(lastResult.status).toBe('matched');
  const first = lastResult.parlay;
  await textbox.fill('cambia el segundo partido');
  await page.getByRole('button', { name: 'Enviar mensaje' }).click();
  await expect(page.locator('.chat-entry.assistant')).toHaveCount(2);
  expect(lastPrevious.id).toBe(first.id);
  const changed = lastResult.parlay || lastResult.alternatives[0];
  expect(changed.legs[0].id).toBe(first.legs[0].id);
  expect(changed.legs[1].eventId).not.toBe(first.legs[1].eventId);
  await textbox.fill('quita el tenis');
  await page.getByRole('button', { name: 'Enviar mensaje' }).click();
  await expect(page.locator('.chat-entry.assistant')).toHaveCount(3);
  const removed = lastResult.parlay || lastResult.alternatives[0];
  expect(removed.legs.every(leg => leg.sport === 'basketball')).toBe(true);
  await expect(page.locator('.chat-entry.assistant').last().locator('.filter-summary').first()).toContainText('Básquetbol');
});

test('un fallo del proveedor se muestra y permite reintentar', async ({ page }) => {
  await page.route('**/api/parlays/daily?**', route => route.fulfill({ status: 503, contentType: 'application/json', body: JSON.stringify({ error: 'Proveedor no disponible temporalmente.', code: 'PROVIDER_UNAVAILABLE' }) }));
  await page.goto('/');
  await expect(page.getByRole('alert')).toContainText('Proveedor no disponible temporalmente.');
  await expect(page.locator('.parlay-card')).toHaveCount(0);
  await page.unroute('**/api/parlays/daily?**');
  await page.getByRole('button', { name: /Reintentar/ }).click();
  await expect(page.locator('.parlay-card')).toHaveCount(6);
});

test('vista móvil permite navegar y crear sin desbordamiento horizontal', async ({ page }) => {
  await page.setViewportSize({ width: 375, height: 812 });
  await page.goto('/');
  await expect(page.locator('.parlay-card').first()).toBeVisible();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  await page.locator('.mobile-nav').getByRole('button', { name: 'Constructor' }).click();
  await expect(page.getByRole('heading', { name: 'Tu combinada. Tus condiciones.' })).toBeVisible();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  await page.locator('button[type="submit"]').click();
  await expect(page.getByRole('heading', { name: 'Una combinada a tu medida.' })).toBeVisible();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  await page.locator('.mobile-nav').getByRole('button', { name: 'Chat IA' }).click();
  await expect(page.getByText('IA pendiente de conexión')).toBeVisible();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
});
